// src/types.ts
export interface User {
    id: number;
    username: string;
    special_id: string;
    income: string;
    account_number: string;
    banks: string;
    marital: string;
    children: string;
    phone_number: string;
    firstName: string;
    mailExtension: string;
    residence: string;
    bvn_number: string;
    gender: string;
    education: string;
    organization: string;
    employment: string;
    sector: string;
    loan: string;
    duration: string;
    guarantor_name: string;
    guarantor_number: string;
    relationship: string;
    email: string;
    date_joined: string;
    user_status: string;
}
